dist: xenial
language: cpp
compiler:
- gcc
os:
- linux
before_install:
  - sudo apt-get update -y
  - sudo apt-get install flex bison make libboost-all-dev libgsl-dev ghc
  - git clone https://github.com/jlab/gapc /home/travis/gapc
  - pushd .
  - cd /home/travis/gapc
  - ./configure
  - make
  - sudo make install
  - popd
before_script:
  # point to Bellmans's GAP install directory:
  - sed -i "s#bgapDir = '/vol/gapc/'#bgapDir = '/usr/local/'#" Misc/Applications/lib/foldGrammars/Settings.pm
  # point to fold-grammars source directory:
  - sed -i "s#rootDir = '/vol/fold-grammars/src/'#rootDir = '`pwd`/'#" Misc/Applications/lib/foldGrammars/Settings.pm
script:
  - cd Misc/Test-Suite/StefanStyle/ && perl runTests.pl
  #- make test -j `nproc --all`
  - echo "hier bin ich"
